import { EventInfo } from './event-info';

export const EVENTS: EventInfo[] = [
    {
	// "created": 1528349407000,
	// "duration": 7200000,
	// "id": "251505322",
	"name": "Music Lounge",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1530151200000,
	// "local_date": "2018-06-27",
	// "local_time": "19:00",
	// "rsvp_close_offset": "PT30H",
	// "updated": 1529531616000,
	// "utc_offset": -25200000,
	// "waitlist_count": 11,
	// "yes_rsvp_count": 9,
	// "venue": {
	//     "id": 2755671,
	//     "name": "Villa Del Sol Apartments",
	//     "lat": 37.376842498779,
	//     "lon": -122.02647399902,
	//     "repinned": true,
	//     "address_1": "355 East Evelyn Avenue",
	//     "city": "Sunnyvale",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "94086",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251505322\/",
	"description": "<p>Music Lounge is a loosely structured music sharing session in the hopes of expanding everyone's horizons in the art of sound.<\/p> <p>Bring a song that's thought-provoking, heart-wrenching, jaw-dropping, mind-blowing, or one that you just enjoy to share with the group! No genre is off-limits.<\/p> <p>Come with an open mind to listen to others' music and refrain from initial judgement. Discussion of the song after each play is encouraged but voluntary.<\/p> <p>=======================================================================<br\/>Notes:<br\/>1. Please update your attendance if your plans change as spots are limited!<\/p> <p>2. Please BYOB and chairs, or feel free to chill on the floor.<\/p> ",
	// "how_to_find_us": "The apartment is at 395 East Evelyn Ave. I'll send out more details and my phone number on the day. ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471812760,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/f\/f\/8\/highres_471812760.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/f\/f\/8\/600_471812760.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/f\/f\/8\/thumb_471812760.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1527889189000,
	// "duration": 7200000,
	// "fee": {
	//     "accepts": "cash",
	//     "amount": 20,
	//     "currency": "USD",
	//     "description": "",
	//     "label": "Price",
	//     "required": false
	// },
	// "id": "251313629",
	"name": "Clue Mystery Party",
	// "rsvp_limit": 15,
	// "status": "upcoming",
	"time": 1530410400000,
	// "local_date": "2018-06-30",
	// "local_time": "19:00",
	// "updated": 1530068751000,
	// "utc_offset": -25200000,
	// "waitlist_count": 2,
	// "yes_rsvp_count": 21,
	// "venue": {
	//     "id": 2755671,
	//     "name": "Villa Del Sol Apartments",
	//     "lat": 37.376842498779,
	//     "lon": -122.02647399902,
	//     "repinned": true,
	//     "address_1": "355 East Evelyn Avenue",
	//     "city": "Sunnyvale",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "94086",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251313629\/",
	"description": "<p>Mr. Boddy\u2014apparently the victim of foul play\u2014is found in one of the rooms of his mansion. And you are one of the suspects. To win, you must determine the answers to these three questions: Who done it? Where? And with What Weapon?<\/p> <p>=====<\/p> <p>We will be playing a live-action version of the game Clue! You will be assigned a character role (come dressed the part!) and become a suspect in the game.<\/p> <p>The game will be similar to the original Clue board game, except you will be walking around to the different rooms to do your investigation, and it'll be more fun and interactive! We will explain the rules during the event.<\/p> <p>Snacks and refreshments (wine, hor d'oeuvres, etc.) will be included in the cost ($20). This will be a slightly classy event, so please come dressed the part, and preferably in character.<\/p> <p>=====<\/p> <p>Dress Code:<\/p> <p>Cocktail party-style (but on the more casual end is fine). Try to dress to the part of your character (i.e., wear a color that that matches the character's name). Be creative!<\/p> <p>Cost: $20\/person for food, drinks, and supplies<\/p> <p>When you RSVP, be sure to send $20 to @michelleth through Venmo or PayPal ( <a href=\"http:\/\/paypal.me\/michelleth\/20\" class=\"linkified\">http:\/\/paypal.me\/michelleth\/20<\/a> ).<\/p> <p>=====<\/p> <p>Characters (you may claim one in the comments--any gender is okay):<\/p> <p>Claimed Characters:<\/p> <p>\u2022 M. Alphonse Brunette - Tim<br\/>\u2022 Mrs. Elizabeth Peacock - Courtney<br\/>\u2022 Miss Georgia Peach - My<br\/>\u2022 Mr. Graham Slate-Grey - Jake<br\/>\u2022 Mrs. Ho - SummerGirl (Sonya)<br\/>\u2022 Lady Su Sian Lavender - Eunice<br\/>\u2022 Prof. Peter Plum - Chandler<br\/>\u2022 Ms. Vivienne Scarlett - Bhuvin<br\/>\u2022 Mrs. Blanche White - Jennifer's +1<br\/>\u2022 Rev. Jonathan Green - Karen<br\/>\u2022 Mrs. Jane Meadow-Brook - Gabby<br\/>\u2022 Sgt. Marshall Gray - Francesca's +1<br\/>\u2022 Mr. Miles Meadow-Brook - Kyle<br\/>\u2022 Col. Michael Mustard - Peter<br\/>\u2022 Dr. Orchid - Jennifer<br\/>\u2022 Prince Philippe Azure - Kevin<br\/>\u2022 Mme. Rhoda Rose - Francesca<br\/>\u2022 Captain Robert Brown - Tariq<br\/>\u2022 Mr. Rusty Nayler - Camille<br\/>\u2022 Wadsworth - Vikas<br\/>\u2022 Yvette - Michelle<\/p> <p>_____<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "The apartment is at 395 East Evelyn Ave. I'll send out more details and my phone number on the day. ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471627127,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/6\/9\/f\/7\/highres_471627127.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/6\/9\/f\/7\/600_471627127.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/6\/9\/f\/7\/thumb_471627127.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1528348321000,
	// "duration": 5400000,
	// "id": "251505060",
	"name": "Thought Lounge",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1530491400000,
	// "local_date": "2018-07-01",
	// "local_time": "17:30",
	// "rsvp_close_offset": "PT28H30M",
	// "updated": 1529531663000,
	// "utc_offset": -25200000,
	// "waitlist_count": 8,
	// "yes_rsvp_count": 12,
	// "venue": {
	//     "id": 2755671,
	//     "name": "Villa Del Sol Apartments",
	//     "lat": 37.376842498779,
	//     "lon": -122.02647399902,
	//     "repinned": true,
	//     "address_1": "355 East Evelyn Avenue",
	//     "city": "Sunnyvale",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "94086",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251505060\/",
	"description": "<p>The following is borrowed directly from the Thought Lounge non-profit group (<a href=\"http:\/\/thoughtlounge.org\/\" class=\"linkified\">http:\/\/thoughtlounge.org\/<\/a>):<\/p> <p>A Thought Lounge Session is a lightly structured dialogue in which 3-6 participants (yourself included!) are organized by a Host to meet in person. At the beginning of a TL Session there is an \u201copening one-breath ritual,\u201d in which all participants state how they are feeling and why they came. The Host then goes over the TL 5 Agreements of Dialogue, and each person is invited to lead a 12 minute conversation on a topic that strikes passion in them. After all 3-6 topics have been presented, the Host writes the topics on a whiteboard and participants take an additional 12 minutes to talk about and draw connections between them. At the end of the TL Session there is another \u201cclosing one-breath ritual,\u201d in which participants state how they are feeling after the session, and how they felt it went.<\/p> <p>BRING A TOPIC FOR CONVERSATION that is at the frontier of your mind and close to your heart right now. There are no restrictions on topics. Literally thousands of topics have been brought in the past, from \"is there such thing as romantic love, or is it a compilation of other loves\" to \"the foundations of mathematics\" to \"surfboard shaping\" to \"what is your funniest life moment.\" See <a href=\"http:\/\/thoughtlounge.org\/pasttopics\" class=\"linkified\">http:\/\/thoughtlounge.org\/pasttopics<\/a> for more examples.<\/p> <p>TL Sessions will begin promptly at 5:30, and end at 7:00pm. You MUST be able to stay for the entire duration of the TL Session, or we ask that you wait to sign up until next time.<\/p> <p>=======================================================================<br\/>Notes:<br\/>1. Please update your attendance if your plans change as spots are limited!<\/p> <p>2. Please BYOB and chairs, or feel free to chill on the floor.<\/p> <p>3. We will most likely be grabbing food afterwards in downtown Sunnyvale!<\/p> ",
	// "how_to_find_us": "The apartment is at 395 East Evelyn Ave. I'll send out more details and my phone number on the day. ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471812318,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/e\/3\/e\/highres_471812318.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/e\/3\/e\/600_471812318.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/7\/e\/3\/e\/thumb_471812318.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1529562989000,
	// "duration": 7200000,
	// "fee": {
	//     "accepts": "cash",
	//     "amount": 15,
	//     "currency": "USD",
	//     "description": "",
	//     "label": "Price",
	//     "required": false
	// },
	// "id": "251982006",
	"name": "Offbeat Food Lab: Michelin Junk Food + Dinner Experience",
	// "rsvp_limit": 8,
	// "status": "upcoming",
	"time": 1530928800000,
	// "local_date": "2018-07-06",
	// "local_time": "19:00",
	// "updated": 1529563411000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 8,
	// "venue": {
	//     "id": 2755671,
	//     "name": "Villa Del Sol Apartments",
	//     "lat": 37.376842498779,
	//     "lon": -122.02647399902,
	//     "repinned": false,
	//     "address_1": "355 East Evelyn Avenue",
	//     "city": "Sunnyvale",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "94086",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251982006\/",
	"description": "<p>You are invited to a private, immersive-dining experience where you will have a chance to learn what it takes to plate (junk) food so that they can belong at a Michelin restaurant. The ingredients used are guaranteed to be freshly picked, rich (in calories), and locally sourced (at a nearby grocery store). This will be a true store to table experience.<\/p> <p>Our minimalist modern table experience offers the most intimate, immersive, and cozy experience at Offbeat Fun. At $15 per person, the Offbeat Junk Food Experience is our highest dining expression. Wine and beverage service available at the time of dining. Parties of 8 only.<\/p> <p>A nice dinner and drinks will also be included in the cost.<\/p> <p>So #soign\u00e9.<\/p> <p>=====<\/p> <p>What's on the Menu:<\/p> <p>Specialty crafted appetizers, made with special care and attention from our participants<\/p> <p>Tacos de Carnitas con Salsa Verde<br\/>Vegetarian option available upon request.<br\/>Paired with an aperitif Berry Spritz<\/p> <p>Decadent dessert, made with special care and attention from our participants<\/p> <p>=====<\/p> <p>Inspired by the satirical Chef Jacques la Merde (<a href=\"https:\/\/www.instagram.com\/chefjacqueslamerde\/\" class=\"linkified\">https:\/\/www.instagram.com\/chefjacqueslamerde\/<\/a>), we will attempt to plate junk food to make them look like they belong at a Michelin restaurant. The #gastroart dishes are guaranteed to be #soign\u00e9.<\/p> <p>We will feast on our creations and a homemade dinner by Chef Vikas afterwards.<\/p> <p>Cost: $15 per person for food and drinks<\/p> <p>When you RSVP, be sure to send $15 to @michelleth through Venmo or PayPal ( <a href=\"http:\/\/paypal.me\/michelleth\/15\" class=\"linkified\">http:\/\/paypal.me\/michelleth\/15<\/a> ).<\/p> <p>We need the payments in advance to hold this event, so we will remove your RSVP if we do not receive your payment. Refer to our payment and refund policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> ",
	// "how_to_find_us": "The apartment is at 395 East Evelyn Ave. I'll send out more details and my phone number on the day.",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 472221475,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/3\/e\/3\/highres_472221475.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/3\/e\/3\/600_472221475.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/3\/e\/3\/thumb_472221475.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1530138318000,
	// "duration": 9000000,
	// "id": "252209007",
	"name": "Orienteering Summer Series 2018: Joaquin Miller Park with BAOC",
	// "status": "upcoming",
	"time": 1531067400000,
	// "local_date": "2018-07-08",
	// "local_time": "09:30",
	// "updated": 1530141125000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24831880,
	//     "name": "http:\/\/tinyurl.com\/redwoodglentrailhead",
	//     "lat": 37.813995361328,
	//     "lon": -122.17693328857,
	//     "repinned": false,
	//     "address_1": "Redwood Glen Trailhead in Joaquin Miller Park",
	//     "city": "Oakland",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/252209007\/",
	"description": "<p>\u2022 What we'll do<br\/>Do you enjoy hiking? Do scavenger hunts interest you? If yes, consider orienteering your sport! The Bay Area Orienteering Club (BAOC) is hosting its a C-Meet at Joaquin Miller Park as a part of its Summer Series.<\/p> <p>Enter Joaquin Miller Park and you will quickly forget that you are minutes away from the hustle and bustle of the city. Hikers, equestrians, bicyclists, joggers and picnickers from all over the Bay Area regularly frequent the 500-acre park. The rustic woodland trails lead you through redwood groves and oak woodlands and across lush creeksides and wet meadows.<\/p> <p>Where: We will meet at the Redwood Glen trailhead, which is walking distance from parking.(<a href=\"https:\/\/goo.gl\/maps\/o4J2bZEgDu52\" class=\"linkified\">https:\/\/goo.gl\/maps\/o4J2bZEgDu52<\/a>)<\/p> <p>Sign up to give \/ join a carpool at: <a href=\"https:\/\/www.groupcarpool.com\/t\/f4pb2n\" class=\"linkified\">https:\/\/www.groupcarpool.com\/t\/f4pb2n<\/a> . This is highly recommended for a few reasons: parking will be limited, some of my non meetup friends are carpooling, and we should spare the air! You get picked up from a BART station!<\/p> <p>Joaquin Miller Park Webpage (<a href=\"http:\/\/www2.oaklandnet.com\/government\/o\/opr\/s\/Parks\/JoaquinMiller\/index.htm\" class=\"linkified\">http:\/\/www2.oaklandnet.com\/government\/o\/opr\/s\/Parks\/JoaquinMiller\/index.htm<\/a>) and park map (<a href=\"http:\/\/www2.oaklandnet.com\/oakca1\/groups\/opr\/documents\/agenda\/oak061362.pdf\" class=\"linkified\">http:\/\/www2.oaklandnet.com\/oakca1\/groups\/opr\/documents\/agenda\/oak061362.pdf<\/a>). On that map, our meeting spot is the higher end of the Big Trees trail on Skyline Blvd.<\/p> <p>About the BAOC Summer Series<\/p> <p>We are happy to announce the return of the BAOC Summer Series. This series of moderate-length events will be held from May through August on some of our more-urban and less-steep maps. Thus allowing us to enjoy orienteering during the hotter days of summer.<\/p> <p>From <a href=\"http:\/\/baoc.org\/wiki\/Schedule\/2018\/Summer_Series\" class=\"linkified\">http:\/\/baoc.org\/wiki\/Schedule\/2018\/Summer_Series<\/a><\/p> <p>What is Orienteering?<\/p> <p>In orienteering, you use a map and a compass to locate a series of points shown on a specialized topo map, choosing routes\u2014on or off trail\u2014that will help you find all the points and get to the finish in the shortest amount of time (assuming that you choose to be competitive).<\/p> <p>Each point, or \"control\", is a distinctly mapped feature, such as a stream junction, boulder, or hilltop, and is marked with an orange-and-white flag, or \"bag\".<\/p> <p>From <a href=\"http:\/\/baoc.org\/wiki\/FAQ\" class=\"linkified\">http:\/\/baoc.org\/wiki\/FAQ<\/a><\/p> <p>How to Orienteer?<\/p> <p>Come learn with us at this event!<\/p> <p>Here\u2019s an introductory video (<a href=\"http:\/\/www.howcast.com\/videos\/404244-How-to-Orienteer\" class=\"linkified\">http:\/\/www.howcast.com\/videos\/404244-How-to-Orienteer<\/a>) and the Orienteering USA\u2019s introduction page (<a href=\"http:\/\/orienteeringusa.org\/new-o\/beginners-guide\" class=\"linkified\">http:\/\/orienteeringusa.org\/new-o\/beginners-guide<\/a>).<\/p> <p>\u2022 What to bring<br\/>Bring water, snacks. Hiking clothing and boots are recommended. Orienteering equipment (an E-punch and compass) are optional- they can be rented.<\/p> <p>\u2022 Important to know<br\/>When: Sunday July 8th, 9:30am-12pm<\/p> <p>Cost: Course Fees are $8\/person for beginner courses and $18\/person for advanced courses. In addition, there is a parking fee ($5\/vehicle), a compass rental fee ($1 each), and an E-punch rental ($5 \/team). Jules will provide a compass and a E-punch.<\/p> <p>More info: Learn more about this event and the Bay Area Orienteering Club on their site <a href=\"http:\/\/baoc.org\/wiki\/Schedule\/2018\/Joaquin_Miller\" class=\"linkified\">http:\/\/baoc.org\/wiki\/Schedule\/2018\/Joaquin_Miller<\/a><br\/><a href=\"https:\/\/www.facebook.com\/events\/2057670367838782\" class=\"linkified\">https:\/\/www.facebook.com\/events\/2057670367838782<\/a><\/p> ",
	// "how_to_find_us": "We will meet at the Redwood Glen Trailhead, which is walking distance from parking",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 472423028,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/a\/8\/1\/4\/highres_472423028.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/a\/8\/1\/4\/600_472423028.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/a\/8\/1\/4\/thumb_472423028.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1529563912000,
	// "duration": 10800000,
	// "id": "251982378",
	"name": "Indoor Nerf Battle",
	// "rsvp_limit": 10,
	// "status": "upcoming",
	"time": 1531080000000,
	// "local_date": "2018-07-08",
	// "local_time": "13:00",
	// "updated": 1529614097000,
	// "utc_offset": -25200000,
	// "waitlist_count": 1,
	// "yes_rsvp_count": 10,
	// "venue": {
	//     "id": 2755671,
	//     "name": "Villa Del Sol Apartments",
	//     "lat": 37.376842498779,
	//     "lon": -122.02647399902,
	//     "repinned": false,
	//     "address_1": "355 East Evelyn Avenue",
	//     "city": "Sunnyvale",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "94086",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251982378\/",
	"description": "<p>We have an empty apartment! What better way to say farewell to it than to have an Indoor Nerf Battle?<\/p> <p>We'll hang out and play a variety of Nerf games. Rules will be provided at the event.<\/p> <p>This is a casual free event, so please bring your own equipment. Bring a Nerf gun and ammos if you can. If you can't, tell us in the comment, and we'll see what we can do.<\/p> <p>If you happen to have any boxes, bring those too! We can also build mini forts!<\/p> ",
	// "how_to_find_us": "The apartment is at 395 East Evelyn Ave. I'll send out more details and my phone number on the day.",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 472222230,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/6\/d\/6\/highres_472222230.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/6\/d\/6\/600_472222230.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/5\/6\/d\/6\/thumb_472222230.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1528231163000,
	// "duration": 7200000,
	// "id": "251450280",
	"name": "Wordsmith Wednesday: Creative Writing Games",
	// "rsvp_limit": 9,
	// "status": "upcoming",
	"time": 1531357200000,
	// "local_date": "2018-07-11",
	// "local_time": "18:00",
	// "updated": 1529613333000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 6,
	// "venue": {
	//     "id": 24726641,
	//     "name": "WeWork Valley Towers",
	//     "lat": 37.33708190918,
	//     "lon": -121.88938903809,
	//     "repinned": false,
	//     "address_1": "75 E Santa Clara St. 6th Floor",
	//     "city": "San Jose",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251450280\/",
	"description": "<p>Like to write? Got writer's block? Want to just dip your feet into writing with some fun games? We got you. Come join us as we all get our creative juices going and write.<\/p> <p>The focus on this first writing event will be to play some creative writing games to get the juices flowing. Hopefully you will come away with some fresh ideas for some new creation. Or at least this will help get you back into writing for fun.<\/p> <p>Everyone is welcome, whether you regularly write or not!<\/p> <p>Bring:<br\/>- A photo ID to check in at the front WeWork reception<br\/>- Pen and paper or your laptop--basically anything to write on<\/p> <p>We're also trying out the new WeWork buildings. We'll be in room 6D.<\/p> <p>--<br\/>Are there certain events you want to see? Vote for them or add them here:<br\/><a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "We'll be in Room 6D--make sure to bring a photo ID for WeWork",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471785109,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/1\/3\/f\/5\/highres_471785109.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/1\/3\/f\/5\/600_471785109.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/1\/3\/f\/5\/thumb_471785109.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1527037379000,
	// "duration": 10800000,
	// "fee": {
	//     "accepts": "cash",
	//     "amount": 12,
	//     "currency": "USD",
	//     "description": "",
	//     "label": "Price",
	//     "required": false
	// },
	// "id": "251032895",
	"name": "Offbeat Adventures: Choose Your Own \"Medieval Clans\" Adventure",
	// "status": "upcoming",
	"time": 1531602000000,
	// "local_date": "2018-07-14",
	// "local_time": "14:00",
	// "updated": 1528260046000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 11,
	// "venue": {
	//     "id": 24157816,
	//     "name": "Location TBD",
	//     "lat": 37.999465942383,
	//     "lon": -122.17460632324,
	//     "repinned": true,
	//     "address_1": "Location TBD",
	//     "city": "Bay Area",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/251032895\/",
	"description": "<p>In our first ever Choose Your Own Adventure\/Live RPG type of game, you will be transported back in time to the medieval ages with kings, bandits, and knights (oh my).<\/p> <p>Overview:<br\/>Everyone will start out as normal townsfolk. As the game progresses, you will find loot, complete quests, fight off enemies, and begin to diverge in your life paths. Over time, you will find your role in life as members of different clans... Perhaps you will be the one to lead your clan and unite the whole kingdom!<\/p> <p>Join us for this unique event that was months in the making! Everything will happen very naturally (there are no scripts). This is very much a Choose Your Own Adventure type of game, played out in real-life. What adventure will you choose?<\/p> <p>Come dressed up as medieval characters or other costumes (anything is fair game)! There will be snacks and drinks (non-alcoholic). We'll get dinner afterwards for those who want to stick around.<\/p> <p>This event was created in collaboration with Tyler's Mystery Tours.<\/p> <p>=====<\/p> <p>Cost: $12 per person for supplies and snacks\/drinks<\/p> <p>When you RSVP, be sure to send $12 through Venmo @michelleth or PayPal <a href=\"http:\/\/paypal.me\/michelleth\/12\/\" class=\"linkified\">http:\/\/paypal.me\/michelleth\/12\/<\/a>. We need the payments in advance to hold this event, so we will remove your RSVP if not paid.<\/p> <p>Bring:<br\/>- Come dressed up! Anything is good!<br\/>- Water<\/p> <p>Disclaimer:<br\/>All participants accept sole responsibility for their actions and any consequences that may result. The organizer(s), event host(s), and other members of this group are not liable for any injuries you may sustain, damage you may cause, or criminal charges incurred otherwise while participating in this event. By attending this event, you agree to these terms. You will be required to provide a verbal confirmation accepting this agreement and\/or a signed waiver before being allowed to participate when we meet for this event.<\/p> <p>Are there certain events you want to see? Vote for them or add them here:<br\/><a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "TBD",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471349986,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/c\/3\/4\/2\/highres_471349986.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/c\/3\/4\/2\/600_471349986.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/c\/3\/4\/2\/thumb_471349986.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1522093293000,
	// "duration": 7200000,
	// "id": "krdvmpyxkbbc",
	"name": "Offbeat Movie Night + Potluck",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1532138400000,
	// "local_date": "2018-07-20",
	// "local_time": "19:00",
	// "rsvp_open_offset": "PT343H",
	// "rsvp_close_offset": "PT22H",
	// "updated": 1522093293000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/krdvmpyxkbbc\/",
	"description": "<p>Looking to expand your movie repertoire? Join us for an \"offbeat\" movie night!<\/p> <p>Every 3rd Friday (unless changed), we'll gather and watch a movie that's a little bit \"offbeat\"--meaning movies that are either not mainstream or just plain weird.<\/p> <p>If you have ideas for movies to watch, please submit them in the comments!<\/p> <p>=====<\/p> <p>The movie will start at 8pm.<\/p> <p>Come earlier to hang out and join us for a potluck dinner at 7pm. Please bring some food\/drinks to share if you'll be joining for dinner. Write in the comments the type of food\/drinks you'll be bringing so we don't all bring the same things (e.g., entree, appetizer, dessert, wine, beer)!<\/p> <p>Note: Please keep your RSVP updated! Remove yourself (including from the waitlist) if you will no longer attend. We will assign a strike if you remove your RSVP at the last minute (&amp;lt; 48 hours notice) or if you flake (no-show). If there's a waitlist, we'll assign 2 strikes for any flakes. Don't be flaky!<\/p> <p>RSVPs will open up 2 weeks before the event date.<\/p> <p>See our RSVP policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> <p>--<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 468716545,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/highres_468716545.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/600_468716545.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/thumb_468716545.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1525581598000,
	// "duration": 7200000,
	// "id": "250503803",
	"name": "Play Two Rooms and a Boom",
	// "status": "upcoming",
	"time": 1532296800000,
	// "local_date": "2018-07-22",
	// "local_time": "15:00",
	// "updated": 1527992477000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 19,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/250503803\/",
	"description": "<p>\"In this social game of hidden roles and deduction, players are divided into 2 different rooms. Find your teammates, establish trust, and exchange hostages before time runs out and the bomb explodes!\"<\/p> <p><a href=\"http:\/\/www.tuesdayknightgames.com\/tworoomsandaboom\/\" class=\"linkified\">http:\/\/www.tuesdayknightgames.com\/tworoomsandaboom\/<\/a><\/p> <p>\"In Two Rooms and a Boom there are 2 teams and 2 rooms. The 2 teams are the Blue Team and the Red Team. The Blue Team has a President. The Red Team has a Bomber. Players are first equally distributed between 2 separate playing areas (usually 2 separate rooms) and then each player is randomly dealt a face-down character card.<\/p> <p>Players play the game by saying what they want in order to select a leader for their room. The leader chooses hostages (players who will be sent to the other room at the end of the round).<\/p> <p>The game consists of 3 timed rounds. Each round is shorter than the previous round. At the end of each round, the hostages selected by the leaders will be traded into opposing rooms.<\/p> <p>The game ends after the last hostage exchange.<\/p> <p>Everyone reveals their card. If Red Team\u2019s Bomber is in the same room as the President, then the Red Team wins. Otherwise the Blue Team wins. \"<\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 470837714,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/4\/5\/3\/2\/highres_470837714.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/4\/5\/3\/2\/600_470837714.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/4\/5\/3\/2\/thumb_470837714.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1521253551000,
	// "duration": 7200000,
	// "id": "nslbmpyxkbmc",
	"name": "Monthly Matinee",
	// "status": "upcoming",
	"time": 1532886300000,
	// "local_date": "2018-07-29",
	// "local_time": "10:45",
	// "updated": 1521253551000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 3,
	// "venue": {
	//     "id": 17803922,
	//     "name": "AMC Mercado 20",
	//     "lat": 37.388179779053,
	//     "lon": -121.9836730957,
	//     "repinned": false,
	//     "address_1": "3111 Mission College Blvd",
	//     "city": "Santa Clara",
	//     "country": "US",
	//     "localized_country_name": "USA",
	//     "phone": "(408)919-0282"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/249105264\/",
	"description": "<p>Film:<\/p> <p>Showtime:<\/p> <p>Run time:<br\/>__________<\/p> <p>THIS EVENT WILL REPEAT ON THE 4TH SUNDAY OF EVERY MONTH UNLESS STATED OTHERWISE.<\/p> <p>I watch a lot of movies. Sometimes, I think they're worth seeing in theaters. I opt for weekend morning\/matinee showings because they're cheaper and less crowded. Feel free to join me. I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up.<br\/>__________<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up. My cell is 650-229-4367 if you need to call me.",
	// "visibility": "public"
    },
    {
	// "created": 1525231692000,
	// "duration": 86400000,
	// "id": "250363115",
	"name": "Camping+Meteor Shower",
	// "status": "upcoming",
	"time": 1534014000000,
	// "local_date": "2018-08-11",
	// "local_time": "12:00",
	// "rsvp_close_offset": "PT72H",
	// "updated": 1527138110000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 53,
	// "venue": {
	//     "id": 18355782,
	//     "name": "Pinnacles West Entrance",
	//     "lat": 37.355739593506,
	//     "lon": -121.95498657227,
	//     "repinned": false,
	//     "address_1": "36.477352, -121.226114",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/250363115\/",
	"description": "<p>The Perseid Meteor Shower is by far the best show to see year round. It\u2019s always held in comfortable weather unlike it\u2019s brethren. Hopefully we will be graced with a clear night because we will be under a NEW MOON (that means \u2018no moon\u2019); so the viewing will be truly special and spectacular!!! It\u2019s incredibly rare for the peak of the shower to fall under such prime viewing conditions.<\/p> <p>We will be heading to Pinnacles National Park for this one. The park is known for its seclusion from light pollution, all the better for our viewing and to detach from the buzz of day-to-day life.<\/p> <p>Food\/drink: bring your own. I struggled with this... if most of the group is interested in chipping in further than the $5, i can set something up. Just leave your thoughts in the comments. Otherwise, I felt it was better to not constrain people.<\/p> <p>For the adventurers, we will be hiking to the peak in the cloak of darkness to view the show. Make sure to pack lighting if you plan to join in. Departure 10pm-ish.<\/p> <p>Parking will be limited. A carpool sheet and rendezvous points will be set up. Each car will be charged $25 entrance fee. Please chip in for fees and gas to your driver.<\/p> <p>A sheet for tent sharing will be posted. Please list if you can supply a tent or need to share space. There is a limit to the number of tents a campsite is allowed, so please don\u2019t rely on sleeping solo. Star sleepers can do whatever you want \ud83d\ude43.<\/p> <p>For purposes of securing the campsites, I will need to collect a whopping $5 from each person. Venmo your dollars to Vuhuynh101@gmail.com.<\/p> ",
	// "visibility": "public"
    },
    {
	// "created": 1522093293000,
	// "duration": 7200000,
	// "id": "krdvmpyxlbwb",
	"name": "Offbeat Movie Night + Potluck",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1534557600000,
	// "local_date": "2018-08-17",
	// "local_time": "19:00",
	// "rsvp_open_offset": "PT343H",
	// "rsvp_close_offset": "PT22H",
	// "updated": 1522093293000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/krdvmpyxlbwb\/",
	"description": "<p>Looking to expand your movie repertoire? Join us for an \"offbeat\" movie night!<\/p> <p>Every 3rd Friday (unless changed), we'll gather and watch a movie that's a little bit \"offbeat\"--meaning movies that are either not mainstream or just plain weird.<\/p> <p>If you have ideas for movies to watch, please submit them in the comments!<\/p> <p>=====<\/p> <p>The movie will start at 8pm.<\/p> <p>Come earlier to hang out and join us for a potluck dinner at 7pm. Please bring some food\/drinks to share if you'll be joining for dinner. Write in the comments the type of food\/drinks you'll be bringing so we don't all bring the same things (e.g., entree, appetizer, dessert, wine, beer)!<\/p> <p>Note: Please keep your RSVP updated! Remove yourself (including from the waitlist) if you will no longer attend. We will assign a strike if you remove your RSVP at the last minute (&amp;lt; 48 hours notice) or if you flake (no-show). If there's a waitlist, we'll assign 2 strikes for any flakes. Don't be flaky!<\/p> <p>RSVPs will open up 2 weeks before the event date.<\/p> <p>See our RSVP policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> <p>--<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 468716545,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/highres_468716545.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/600_468716545.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/thumb_468716545.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1526580864000,
	// "duration": 10800000,
	// "id": "250882952",
	"name": "Offbeat wood refinishing",
	// "status": "upcoming",
	"time": 1535227200000,
	// "local_date": "2018-08-25",
	// "local_time": "13:00",
	// "updated": 1526581109000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 2,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/250882952\/",
	"description": "<p>We're going to refinish a dining room table.<\/p> <p>Haven't decided how to make thing a group event. Detail to come.<\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 471188292,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/2\/0\/6\/4\/highres_471188292.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/2\/0\/6\/4\/600_471188292.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/2\/0\/6\/4\/thumb_471188292.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1521253551000,
	// "duration": 7200000,
	// "id": "nslbmpyxlbjc",
	"name": "Monthly Matinee",
	// "status": "upcoming",
	"time": 1535305500000,
	// "local_date": "2018-08-26",
	// "local_time": "10:45",
	// "updated": 1521253551000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 2,
	// "venue": {
	//     "id": 17803922,
	//     "name": "AMC Mercado 20",
	//     "lat": 37.388179779053,
	//     "lon": -121.9836730957,
	//     "repinned": false,
	//     "address_1": "3111 Mission College Blvd",
	//     "city": "Santa Clara",
	//     "country": "US",
	//     "localized_country_name": "USA",
	//     "phone": "(408)919-0282"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/249105265\/",
	"description": "<p>Film:<\/p> <p>Showtime:<\/p> <p>Run time:<br\/>__________<\/p> <p>THIS EVENT WILL REPEAT ON THE 4TH SUNDAY OF EVERY MONTH UNLESS STATED OTHERWISE.<\/p> <p>I watch a lot of movies. Sometimes, I think they're worth seeing in theaters. I opt for weekend morning\/matinee showings because they're cheaper and less crowded. Feel free to join me. I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up.<br\/>__________<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up. My cell is 650-229-4367 if you need to call me.",
	// "visibility": "public"
    },
    {
	// "created": 1522093293000,
	// "duration": 7200000,
	// "id": "krdvmpyxmbcc",
	"name": "Offbeat Movie Night + Potluck",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1537581600000,
	// "local_date": "2018-09-21",
	// "local_time": "19:00",
	// "rsvp_open_offset": "PT343H",
	// "rsvp_close_offset": "PT22H",
	// "updated": 1522093293000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/krdvmpyxmbcc\/",
	"description": "<p>Looking to expand your movie repertoire? Join us for an \"offbeat\" movie night!<\/p> <p>Every 3rd Friday (unless changed), we'll gather and watch a movie that's a little bit \"offbeat\"--meaning movies that are either not mainstream or just plain weird.<\/p> <p>If you have ideas for movies to watch, please submit them in the comments!<\/p> <p>=====<\/p> <p>The movie will start at 8pm.<\/p> <p>Come earlier to hang out and join us for a potluck dinner at 7pm. Please bring some food\/drinks to share if you'll be joining for dinner. Write in the comments the type of food\/drinks you'll be bringing so we don't all bring the same things (e.g., entree, appetizer, dessert, wine, beer)!<\/p> <p>Note: Please keep your RSVP updated! Remove yourself (including from the waitlist) if you will no longer attend. We will assign a strike if you remove your RSVP at the last minute (&amp;lt; 48 hours notice) or if you flake (no-show). If there's a waitlist, we'll assign 2 strikes for any flakes. Don't be flaky!<\/p> <p>RSVPs will open up 2 weeks before the event date.<\/p> <p>See our RSVP policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> <p>--<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 468716545,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/highres_468716545.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/600_468716545.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/thumb_468716545.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1521253551000,
	// "duration": 7200000,
	// "id": "nslbmpyxmbnc",
	"name": "Monthly Matinee",
	// "status": "upcoming",
	"time": 1538329500000,
	// "local_date": "2018-09-30",
	// "local_time": "10:45",
	// "updated": 1521253551000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 2,
	// "venue": {
	//     "id": 17803922,
	//     "name": "AMC Mercado 20",
	//     "lat": 37.388179779053,
	//     "lon": -121.9836730957,
	//     "repinned": false,
	//     "address_1": "3111 Mission College Blvd",
	//     "city": "Santa Clara",
	//     "country": "US",
	//     "localized_country_name": "USA",
	//     "phone": "(408)919-0282"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/249105266\/",
	"description": "<p>Film:<\/p> <p>Showtime:<\/p> <p>Run time:<br\/>__________<\/p> <p>THIS EVENT WILL REPEAT ON THE 4TH SUNDAY OF EVERY MONTH UNLESS STATED OTHERWISE.<\/p> <p>I watch a lot of movies. Sometimes, I think they're worth seeing in theaters. I opt for weekend morning\/matinee showings because they're cheaper and less crowded. Feel free to join me. I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up.<br\/>__________<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up. My cell is 650-229-4367 if you need to call me.",
	// "visibility": "public"
    },
    {
	// "created": 1522093293000,
	// "duration": 7200000,
	// "id": "krdvmpyxnbzb",
	"name": "Offbeat Movie Night + Potluck",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1540000800000,
	// "local_date": "2018-10-19",
	// "local_time": "19:00",
	// "rsvp_open_offset": "PT343H",
	// "rsvp_close_offset": "PT22H",
	// "updated": 1522093293000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/krdvmpyxnbzb\/",
	"description": "<p>Looking to expand your movie repertoire? Join us for an \"offbeat\" movie night!<\/p> <p>Every 3rd Friday (unless changed), we'll gather and watch a movie that's a little bit \"offbeat\"--meaning movies that are either not mainstream or just plain weird.<\/p> <p>If you have ideas for movies to watch, please submit them in the comments!<\/p> <p>=====<\/p> <p>The movie will start at 8pm.<\/p> <p>Come earlier to hang out and join us for a potluck dinner at 7pm. Please bring some food\/drinks to share if you'll be joining for dinner. Write in the comments the type of food\/drinks you'll be bringing so we don't all bring the same things (e.g., entree, appetizer, dessert, wine, beer)!<\/p> <p>Note: Please keep your RSVP updated! Remove yourself (including from the waitlist) if you will no longer attend. We will assign a strike if you remove your RSVP at the last minute (&amp;lt; 48 hours notice) or if you flake (no-show). If there's a waitlist, we'll assign 2 strikes for any flakes. Don't be flaky!<\/p> <p>RSVPs will open up 2 weeks before the event date.<\/p> <p>See our RSVP policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> <p>--<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 468716545,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/highres_468716545.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/600_468716545.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/thumb_468716545.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    },
    {
	// "created": 1521253551000,
	// "duration": 7200000,
	// "id": "nslbmpyxnblc",
	"name": "Monthly Matinee",
	// "status": "upcoming",
	"time": 1540748700000,
	// "local_date": "2018-10-28",
	// "local_time": "10:45",
	// "updated": 1521253551000,
	// "utc_offset": -25200000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 2,
	// "venue": {
	//     "id": 17803922,
	//     "name": "AMC Mercado 20",
	//     "lat": 37.388179779053,
	//     "lon": -121.9836730957,
	//     "repinned": false,
	//     "address_1": "3111 Mission College Blvd",
	//     "city": "Santa Clara",
	//     "country": "US",
	//     "localized_country_name": "USA",
	//     "phone": "(408)919-0282"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/249105269\/",
	"description": "<p>Film:<\/p> <p>Showtime:<\/p> <p>Run time:<br\/>__________<\/p> <p>THIS EVENT WILL REPEAT ON THE 4TH SUNDAY OF EVERY MONTH UNLESS STATED OTHERWISE.<\/p> <p>I watch a lot of movies. Sometimes, I think they're worth seeing in theaters. I opt for weekend morning\/matinee showings because they're cheaper and less crowded. Feel free to join me. I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up.<br\/>__________<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "how_to_find_us": "I will arrive early and hang out in the lobby to the right of the entrance. At 15 minutes prior to the listed showtime, I will enter the theater to take my seat whether or not anyone else shows up. My cell is 650-229-4367 if you need to call me.",
	// "visibility": "public"
    },
    {
	// "created": 1522093293000,
	// "duration": 7200000,
	// "id": "krdvmpyxpbvb",
	"name": "Offbeat Movie Night + Potluck",
	// "rsvp_limit": 12,
	// "status": "upcoming",
	"time": 1542423600000,
	// "local_date": "2018-11-16",
	// "local_time": "19:00",
	// "rsvp_open_offset": "PT343H",
	// "rsvp_close_offset": "PT22H",
	// "updated": 1522093293000,
	// "utc_offset": -28800000,
	// "waitlist_count": 0,
	// "yes_rsvp_count": 1,
	// "venue": {
	//     "id": 24868710,
	//     "name": "Somewhere in Santa Clara",
	//     "lat": 37.354106903076,
	//     "lon": -121.95523834229,
	//     "repinned": false,
	//     "address_1": "Emailed on day of event",
	//     "city": "Santa Clara",
	//     "country": "us",
	//     "localized_country_name": "USA",
	//     "zip": "",
	//     "state": "CA"
	// },
	// "group": {
	//     "created": 1421912683000,
	//     "name": "Silicon Valley Offbeat Fun for 20s & 30s",
	//     "id": 18365931,
	//     "join_mode": "open",
	//     "lat": 37.349998474121,
	//     "lon": -121.98000335693,
	//     "urlname": "Offbeat-Fun",
	//     "who": "Cool weirdos",
	//     "localized_location": "Santa Clara, CA",
	//     "region": "en_US"
	// },
	// "link": "https:\/\/www.meetup.com\/Offbeat-Fun\/events\/krdvmpyxpbvb\/",
	"description": "<p>Looking to expand your movie repertoire? Join us for an \"offbeat\" movie night!<\/p> <p>Every 3rd Friday (unless changed), we'll gather and watch a movie that's a little bit \"offbeat\"--meaning movies that are either not mainstream or just plain weird.<\/p> <p>If you have ideas for movies to watch, please submit them in the comments!<\/p> <p>=====<\/p> <p>The movie will start at 8pm.<\/p> <p>Come earlier to hang out and join us for a potluck dinner at 7pm. Please bring some food\/drinks to share if you'll be joining for dinner. Write in the comments the type of food\/drinks you'll be bringing so we don't all bring the same things (e.g., entree, appetizer, dessert, wine, beer)!<\/p> <p>Note: Please keep your RSVP updated! Remove yourself (including from the waitlist) if you will no longer attend. We will assign a strike if you remove your RSVP at the last minute (&amp;lt; 48 hours notice) or if you flake (no-show). If there's a waitlist, we'll assign 2 strikes for any flakes. Don't be flaky!<\/p> <p>RSVPs will open up 2 weeks before the event date.<\/p> <p>See our RSVP policy here: <a href=\"https:\/\/www.meetup.com\/Offbeat-Fun\/about\/\" class=\"linkified\">https:\/\/www.meetup.com\/Offbeat-Fun\/about\/<\/a><\/p> <p>--<\/p> <p>Are there certain events you want to see? Vote for them or add them here: <a href=\"http:\/\/tinyurl.com\/OffbeatFunWishlist\" class=\"linkified\">http:\/\/tinyurl.com\/OffbeatFunWishlist<\/a><\/p> ",
	// "visibility": "public",
	"featured_photo": {
	    // "id": 468716545,
	    // "highres_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/highres_468716545.jpeg",
	    "photo_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/600_468716545.jpeg",
	    // "thumb_link": "https:\/\/secure.meetupstatic.com\/photos\/event\/d\/c\/e\/1\/thumb_468716545.jpeg",
	    // "type": "event",
	    // "base_url": "https:\/\/secure.meetupstatic.com"
	}
    }
];
